### PR TITLE
commented check_result_buffer_slots because no longer available in Nagios 3.5.0

### PR DESCRIPTION
**Pull request by cleverlight**
Starting Nagios 3.5.0 fails citing an error at line 402 in files/configs/CentOS/nagios.cfg.  This branch fixes that error by commenting the check_result_buffer_slots directive.

### CODE REVIEW

**Comment by duritong** [comment]
Thank you for your contribution. Wouldn't it then make sense to clear it completely? Also: maybe we should ship a dedicated config for EL6 as EPEL EL5 does not (yet) ship 3.5 and I think EPEL is what most people attach additionally. What do you think?

**Comment by cleverlight** [comment]
Good point.  Yes, we should remove it all together, but I'm not sure how to
handle the multiple version issue.  We could branch the config, which would
mean maintaining a <=EL5 version and a >=EL6 version, or we could change
the file to a template and use a fact to differentiate?  Which do you think
is better?

On 18 June 2013 05:52, duritong notifications@github.com wrote:

> Thank you for your contribution. Wouldn't it then make sense to clear it
> completely? Also: maybe we should ship a dedicated config for EL6 as EPEL
> EL5 does not (yet) ship 3.5 and I think EPEL is what most people attach
> additionally. What do you think?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/duritong/puppet-nagios/pull/7#issuecomment-19590859
> .

## 

Alex Stanhope
Lightenna Ltd http://www.lightenna.com/
07966 798292
0207 183 5698

**Comment by duritong** [comment]
For static files I usually do it within the multisource select. So we should probably add another one before the OS source, like:

<code>
                        "puppet:///modules/nagios/configs/${::operatingsystem}.${operatingsystemmajrelease}/nagios.cfg",
                        "puppet:///modules/nagios/configs/${::operatingsystem}/nagios.cfg",
</code>

And then move the EL5 five to `files/config/CentOS.5/nagios.cfg and include a proper EL 6 one in the place of the old one.

**Comment by duritong** [comment]
Do you still like that to happen? Otherwise I would close it.

**Comment by cleverlight** [comment]
Hi there,

I think I worked around it, so it's not a priority for me thanks.  Feel
free to close it.

Cheers, Alex

**Comment by duritong** [comment]
close

**Pull request closed without merging**
